# Generated by Django 4.2.4 on 2023-08-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lab', models.CharField(max_length=50, verbose_name='NOMBRE LABORATORIO')),
                ('ciudad', models.CharField(max_length=50, verbose_name='CIUDAD')),
                ('pais', models.CharField(max_length=50, verbose_name='PAIS')),
            ],
            options={
                'db_table': 'Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='NOMBRE PRODUCTO')),
                ('f_fabricacion', models.DateField(blank=True, null=True, verbose_name='AÑO FABRICACION')),
                ('p_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PRECIO COSTO')),
                ('p_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PRECIO VENTA')),
                ('laboratorio_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_laboratorio', to='mantenedor_lab.laboratorio', verbose_name='LABORATORIO FABRICACION')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='NOMBRE DIRECTOR')),
                ('especialidad', models.CharField(max_length=50, verbose_name='ESPECIALIDAD')),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directores_generales', to='mantenedor_lab.laboratorio', verbose_name='LABORATORIO ASOCIADO')),
            ],
            options={
                'db_table': 'Director General',
            },
        ),
    ]
