# Generated by Django 4.1.1 on 2023-08-10 21:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(blank=True, error_messages={'invalid': 'La fecha debe ser posterior a 2015.', 'min_value': 'La fecha debe ser posterior a 2015.'}, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2015, 1, 1))], verbose_name='AÑO FABRICACION'),
        ),
    ]
